import { PrismaService } from '../../config/prisma.service';
import { CreateReportDto, UpdateReportDto, ReportResponseDto, ReportListQueryDto, ReportListResponseDto, CreateScheduleDto, UpdateScheduleDto, ScheduleResponseDto, GenerateReportDto, ReportGenerationResponseDto } from './dto/report.dto';
import { AnalyticsService } from './analytics.service';
import { MetricsService } from './metrics.service';
export declare class ReportsService {
    private prisma;
    private analyticsService;
    private metricsService;
    private readonly logger;
    private scheduledJobs;
    constructor(prisma: PrismaService, analyticsService: AnalyticsService, metricsService: MetricsService);
    createReport(userId: string, data: CreateReportDto): Promise<ReportResponseDto>;
    getReports(userId: string, query: ReportListQueryDto): Promise<ReportListResponseDto>;
    getReport(reportId: string, userId: string): Promise<ReportResponseDto | null>;
    updateReport(reportId: string, userId: string, data: UpdateReportDto): Promise<ReportResponseDto>;
    deleteReport(reportId: string, userId: string): Promise<void>;
    generateReport(userId: string, data: GenerateReportDto): Promise<ReportGenerationResponseDto>;
    private processReportGeneration;
    createSchedule(data: CreateScheduleDto): Promise<ScheduleResponseDto>;
    updateSchedule(scheduleId: string, data: UpdateScheduleDto): Promise<ScheduleResponseDto>;
    deleteSchedule(scheduleId: string): Promise<void>;
    private initializeScheduledReports;
    private startScheduledReport;
    private stopScheduledReport;
    private executeScheduledReport;
    private generateSalesReport;
    private generateInventoryReport;
    private generateCustomerReport;
    private generateMerchantReport;
    private generateProductPerformanceReport;
    private generateFinancialReport;
    private generateOperationalReport;
    private generateExecutiveSummary;
    private generateReportFile;
    private sendReportToRecipients;
    private calculateNextRun;
    private mapReportToResponse;
    private mapScheduleToResponse;
}
