version: '3.8'

services:
  api:
    container_name: sunest-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sunest?schema=public
      - NODE_ENV=development
      - JWT_SECRET=development-secret-change-in-production
      - JWT_EXPIRATION=3600
      - JWT_REFRESH_EXPIRATION=86400
      - PORT=3000

  postgres:
    container_name: sunest-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sunest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: