import { PrismaService } from '../../config/prisma.service';
import { MailgunService } from './mailgun.service';
import { NotificationService } from './notification.service';
import { NotificationCategory } from '@prisma/client';
import { CreateNotificationDto, NotificationResponseDto, NotificationListQueryDto, NotificationListResponseDto, UpdateNotificationDto, BulkNotificationDto } from './dto/notification.dto';
import { CreateTemplateDto, UpdateTemplateDto, TemplateResponseDto, TemplateListQueryDto, TemplateListResponseDto, RenderTemplateDto, RenderedTemplateDto } from './dto/template.dto';
import { CreatePreferenceDto, PreferenceResponseDto, BulkPreferenceUpdateDto } from './dto/preference.dto';
import { CreateEventDto, EventResponseDto, EventListQueryDto, EventListResponseDto, EventStatsDto } from './dto/event.dto';
import { QueueEmailDto, EmailQueueResponseDto, EmailQueueListQueryDto, EmailQueueListResponseDto, EmailStatsDto } from './dto/email.dto';
export declare class EnhancedNotificationService {
    private prisma;
    private mailgunService;
    private notificationService;
    private readonly logger;
    constructor(prisma: PrismaService, mailgunService: MailgunService, notificationService: NotificationService);
    createNotification(data: CreateNotificationDto): Promise<NotificationResponseDto>;
    sendNotification(notificationId: string): Promise<boolean>;
    getNotifications(query: NotificationListQueryDto): Promise<NotificationListResponseDto>;
    updateNotification(notificationId: string, data: UpdateNotificationDto): Promise<NotificationResponseDto>;
    createBulkNotifications(data: BulkNotificationDto): Promise<NotificationResponseDto[]>;
    createTemplate(data: CreateTemplateDto): Promise<TemplateResponseDto>;
    getTemplates(query: TemplateListQueryDto): Promise<TemplateListResponseDto>;
    updateTemplate(templateId: string, data: UpdateTemplateDto): Promise<TemplateResponseDto>;
    renderTemplate(templateId: string, data: RenderTemplateDto): Promise<RenderedTemplateDto>;
    createOrUpdatePreference(userId: string, data: CreatePreferenceDto): Promise<PreferenceResponseDto>;
    getUserPreferences(userId: string, category?: NotificationCategory): Promise<{
        category: import(".prisma/client").$Enums.NotificationCategory;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        userId: string;
        channels: import(".prisma/client").$Enums.NotificationChannel[];
        emailEnabled: boolean;
        smsEnabled: boolean;
        pushEnabled: boolean;
        inAppEnabled: boolean;
        quietHoursStart: string | null;
        quietHoursEnd: string | null;
        timezone: string | null;
        emailDigest: boolean;
        digestFrequency: string | null;
    }[]>;
    updateBulkPreferences(userId: string, data: BulkPreferenceUpdateDto): Promise<PreferenceResponseDto[]>;
    createEvent(data: CreateEventDto): Promise<EventResponseDto>;
    getEvents(query: EventListQueryDto): Promise<EventListResponseDto>;
    getEventStats(): Promise<EventStatsDto>;
    queueEmail(data: QueueEmailDto): Promise<EmailQueueResponseDto>;
    sendQueuedEmail(emailId: string): Promise<boolean>;
    getEmailQueue(query: EmailQueueListQueryDto): Promise<EmailQueueListResponseDto>;
    getEmailStats(): Promise<EmailStatsDto>;
    private sendEmailNotification;
    private sendInAppNotification;
    private sendSMSNotification;
    private sendPushNotification;
    private sendWebhookNotification;
    private isChannelAllowed;
    private processEventRules;
    private evaluateConditions;
    private isInCooldown;
    private sendRuleNotifications;
    private renderString;
    private mapNotificationToResponse;
    private mapTemplateToResponse;
    private mapPreferenceToResponse;
    private mapEventToResponse;
    private mapEmailQueueToResponse;
}
